### PR TITLE
support for i18n solutions

### LINKED ISSUE #9: i18n message example
Spoke to @stefanpenner awhile back about this, and sticking to my word to investigate it.

Will poke at it at some point this week to see how we'll be able to leverage the services of ember-intl || ember-i18n to resolve translation keys and handle formatting with params.

### PR DESCRIPTION
**Pull request by offirgolan**
* Create extendable hook for ember-i18n solutions
* Removed String.fmt dependency
* Better ability to extend message strings and add new ones
* Updated docs and added tests

Should resolve #9, #33

### CODE REVIEW

**Comment by offirgolan** [comment]
Ready for review!

@jasonmit let me know what you think.

**Comment by jasonmit** [comment]
Looks good.  My idea was slightly different in exposing a  virtual method that would allow a consumer, or and addon, to implement.  This way it can scale for anyone needing to add some custom logic between the validation message creation process.

Sorry on phone so can't go too into detail.

**Comment by blimmer** [comment]
I agree that it might be nice to tell the app (in an initializer?) which i18n solution (if any) you're using, and plug in support for that library. All that would do would be to essentially implement the call before this [fallback logic](https://github.com/offirgolan/ember-cp-validations/pull/43/files#diff-ae771607a0869c29daefee660de55711R47). That way you could easily add support for other i18n solutions without needing to pull it into core.

Good work so far, this seems like a step in the right direction, and perhaps the adapter style could be a future improvement.

**Comment by jasonmit** [comment]
I am just opposed to the idea that ember-cp-validations has knowledge of ember-intl, ember-i18n, or any third party packages API.  The reason being, different versions of ember-intl, and I assume ember-i18n, have different method signatures.  When either of us changes the API, this lib will also break and would require a pull request to fix since there is no npm dep on either, rightfully so, enforcing versioning.

I think exposing just a method that can be overridden/implemented is the way to go.  For example, I would ship `ember-intl-cp-validations` which would reopen and replace/implement this method.  This methods sole purpose is to intercept the error message generation/lookup and return an error msg as a string.  This would allow you to continue to use Ember.string.fmt and for any arbitrary third party addon to implement their own custom logic while keeping ember-cp-validations decoupled.

If you do with this approach, any change would require a major version release since it would be immediately API breaking.

**Comment by offirgolan** [comment]
Ah okay I get what you are saying. So for this PR the getMessageFor would be really simple

```js
getMessageFor(type, context = {}) {
    return this.formatMessage(get(this, type), context);
},
```

But the 2 addons you will make will just overwrite this method? Something like

```js
getMessageFor(type, context = {}) {
    if (intl) {
      let m = intl.exists(key);
      if(!isNone(m)) {
        return intl.formatMessage(m, context);
      }
    }
    return this._super(...arguments); // fallback 
},
```

**Comment by offirgolan** [comment]
As for the `String.fmt`, since it is being deprecated, I think we should move away from it rather than creating a polyfill.

**Comment by jasonmit** [comment]
> But the 2 addons you will make will just overwrite this method? Something like

Yessir

**Comment by offirgolan** [comment]
Okay just removed the i18n logic. If I get the :+1: we can go ahead and merge this so we can build the Ember-Intl and Ember-I18n cp-addons. Once those get released, Ill update docs and we can issue a 2.0.0 release.

**Comment by jasonmit** [comment]
You have my thumbs up for what it's worth

**Comment by blimmer** [comment]
I think this solution is going to be much better - nicely decoupled. :+1:

**Comment by offirgolan** [comment]
Alright Im gonna go ahead and merge this. @jasonmit im gonna create an issue to track the status of the two addons. Let me know if you need any help

**Pull request merged**
