### PR TITLE
[WIP] hasValidated property 

### PR DESCRIPTION
**Pull request by acburdine**
refs #113 

@offirgolan this is a result of the little bit of time I was able to spend on this, it doesn't work very well at the moment because I'm still getting used to the codebase but will see what all I can do tonight/later this week.

### CODE REVIEW

**Comment by acburdine** [comment]
@offirgolan I've managed to get this working for everything but the hasMany validator; however, the current handling of belongsTo validators isn't ideal, and I may need some guidance as to a better way to accomplish this 😕

**Comment by offirgolan** [comment]
@acburdine super sorry for such a delayed response! Thank you so much for taking the time to put this together. 

I feel as though this is overly complicated, but then again, my use-cases in the past have been very simple. Why is there a need to reset `hasValidated` when a value changes? Maybe `hasValidated` isnt the correct name for this. 

//cc @jasonmit

**Comment by acburdine** [comment]
@offirgolan The reason hasValidated is reset when the value changes is because of [this comment](https://github.com/offirgolan/ember-cp-validations/issues/113#issuecomment-181717343).

Personally, my use case is for only showing the error once the input has focused out, which means whenever the `validate` or `validateSync` method is called. I'm not sure what a better name for it would be though 😕

**Comment by offirgolan** [comment]
Haha okay makes sense 😸 . Let me take some time to think about this and get back to you. I feel like this solution can either be simplified or can be split into a `didValidate` and a `hasChanged` sorta thing.

**Comment by offirgolan** [comment]
Im gonna go ahead and close this PR as it is pretty old. @acburdine thanks again for taking the time to put this PR together but as of right now, I think the simplest solution is to track this state on the app-side.

**Pull request closed without merging**
