### PR TITLE
Provide `baseDir` to allow for proper caching.

### PR DESCRIPTION
**Pull request by rwjblue**
Providing this baseDir will allow for changes/upgrades in ember-cp-validations to invalidate template compilation caches.

This is roughly inline with https://github.com/babel/broccoli-babel-transpiler/pull/89 which I am porting to ember-cli-htmlbars and ember-cli-htmlbars-inline-precompile now.

### CODE REVIEW

**Comment by offirgolan** [comment]
@rwjblue 👍 . Ill keep this PR open so we can track the build / test cases

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli-htmlbars/pull/90 adds support for this upstream (and issues a deprecation if `baseDir` is not provided.

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/pull/37 should fix the immediate issue here (I think).  Would love it if you could test/confirm.

**Comment by offirgolan** [comment]
@rwjblue I made some comments on your PR. After I made them locally, all the test cases passed! 🎉

**Comment by rwjblue** [comment]
Awesome, thank you! I'll get that updated shortly.

**Comment by rwjblue** [comment]
OK, those changes were made and released under ember-cli-htmlbars-inline-precompile@0.3.5.

I believe once updated this should pass...

**Comment by rwjblue** [comment]
Just pushed a commit with that version bump.

**Comment by offirgolan** [comment]
@rwjblue issue seems to be resolved. Tests are failing due to #275

**Comment by rinoldsimon** [comment]
I run 

>"ember-cli": "2.7.0",
  "ember-cli-htmlbars": "^1.1.0",
  "ember-cli-htmlbars-inline-precompile": "^0.3.5",

Even now i'm getting deprecation message when starting the ember server !

> DEPRECATION: ember-cli-htmlbars-inline-precompile is opting out of caching due to an AST plugin that does not provide a caching strategy: `v-get`.
DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `v-get`.

**Comment by rwjblue** [comment]
Why would those versions prevent this deprecation? 

The fix for the deprecation (landed in this PR) hasn't been released in a published version yet (I think).

**Pull request merged**
