### PR TITLE
Migration to owners from container

### PR DESCRIPTION
**Pull request by offirgolan**
Resolves issue #74 

@rwjblue let me know what you think

### CODE REVIEW

**Comment by rwjblue** [comment]
> setting a property that has only a getter

Is coming from something passing `container` in to a factory looked up in the container, we make `this.container` a getter (for deprecation purposes) so you can't set it manually.

**Comment by offirgolan** [comment]
Seems like a problem with ember-data. I added matching ember-data dependencies to ember-try but getting 

`ENOENT, no such file or directory '/Users/offirgolan/Documents/Projects/Ember-Components/ember-cp-validations/tmp/funnel-input_base_path-omS83aWT.tmp/0/bower_components/ember-data/ember-data.js.map'`

Ember try config:

```json
{
    name: 'ember-beta',
    dependencies: {
      'ember': 'components/ember#beta',
      'ember-data': 'components/ember-data#beta'
    },
    resolutions: {
      'ember': 'beta',
      'ember-data': 'beta'
    }
  }
```

**Comment by rwjblue** [comment]
@offirgolan - Seems like https://github.com/components/ember-data/issues/32

**Comment by rwjblue** [comment]
The ember-data issue should be fixed by https://github.com/emberjs/data/pull/3944.

**Comment by offirgolan** [comment]
@rwjblue let me know if this looks good to you and ill issue a minor release.

**Comment by rwjblue** [comment]
:+1: - LGTM

**Pull request merged**
