### PR TITLE
Remove lodash requirement.

### PR DESCRIPTION
**Pull request by rwjblue**
Remove lodash requirement.

Addresses #30.

### CODE REVIEW

**Comment by rwjblue** [comment]
Open questions: should we make the steps above a prepublish step and add `lodash` to the `.gitignore`?

I'm generally not a huge fan of inlining someone else's code into my repos, so I kinda think we do want to do this.  It will mean that we cannot point to master via `"ember-cp-validations": "offirgolan/ember-cp-validations"` in `package.json` though...

**Comment by stefanpenner** [comment]
that looks like a crap ton of code to get flatten :P

**Comment by rwjblue** [comment]
@stefanpenner - I'm game to just do a simple internal version of flatten if y'all want. It was fun playing with the custom lodash builds :smile:

**Comment by offirgolan** [comment]
If we are only using flatten, I vote for just creating an internal version. Also, in response to #30, we can opt out of MomentJS and use js Date instead.

**Comment by rwjblue** [comment]
OK, will update to use an internal flatten

**Comment by rwjblue** [comment]
Updated with a super simple flatten implementation. Please review to make sure it meets our requirements (I added a couple of tests with simple scenarios).

**Comment by ivanvotti** [comment]
Thank you, guys. This change makes my vendor.js file 139 Kb lighter.

Here are some numbers I have for minimized vendor.js:
`ember-cp-validations` itself adds just 12 Kb
all its current dependencies (moment.js) add about 42 Kb

`lodash` added about 139 Kb before this PR

**Comment by stefanpenner** [comment]
@ivanvotti we will woke on money next

**Pull request merged**
