### PR TITLE
Changelog.

### LINKED ISSUE #14: Changelog
We should provide a changelog either in the release notes or a CHANGELOG.md file.

### PR DESCRIPTION
**Pull request by blimmer**
Fixes #14.

### CODE REVIEW

**Comment by stefanpenner** [comment]
Lgtm

**Comment by blimmer** [comment]
Bummer that we declared 1.0.0 so early. Our 1.0.1 release breaks semantic versioning with the confirmation validator change. We should beware of this in the future.

**Comment by stefanpenner** [comment]
@blimmer we can always release 2.0 and 3.0 :P

**Comment by blimmer** [comment]
Yeah, bumping the number is not a big deal, but following semantic versioning 1.0.1 should have been 2.0.0 because of breaking api changes.

**Comment by stefanpenner** [comment]
@blimmer lets consider it a "bugfix" then, and do better going forward.

**Comment by blimmer** [comment]
:+1:

**Pull request merged**
