### PR TITLE
fixed moment date parsing deprecations

### PR DESCRIPTION
**Pull request by danielspaniel**
Howdy partner, I fixed those moment issues and also, just for fun .. fixed up usage of resolver and load-initializer to resolve warnings ..

### CODE REVIEW

**Comment by offirgolan** [comment]
Awesome! Thank you for the contribution! :smile_cat:

**Comment by danielspaniel** [comment]
You welcome @offirgolan .. thanks for the great work on this addon!

**Comment by danielspaniel** [comment]
And do you think you can slap together a new patch version so I can more easily start using my cp-validations with the fewer warnings? :)

**Comment by danielspaniel** [comment]
Hiya @offirgolan, you think you can get a path version going today? My kids are refusing to write more code for me unless they get new version of this addon without the moment warnings.  :(

**Comment by offirgolan** [comment]
Lolol yeah no problem. Just release `v2.6.1`

**Pull request merged**
