### PR TITLE
The road to 2.0

### PR DESCRIPTION
**Pull request by offirgolan**
* Updated docs
* Updated changelog
* Added upgrade doc 
* Updated readme

This PR is to get ready for a 2.0 release. I have attempted to add documentation to everything that has been changed + anything that was missing documentation. Check it out and let me know what you guys think because once this is given the go ahead im gonna update the demo and create the 2.0.0 release.

### CODE REVIEW

**Comment by offirgolan** [comment]
@stefanpenner @blimmer

**Comment by offirgolan** [comment]
@jasonmit let me know when you are also done on your end :smile_cat:

**Comment by stefanpenner** [comment]
LGTM

**Comment by jasonmit** [comment]
All done on my end, both libs ready :)

**Comment by offirgolan** [comment]
Sweet thanks again everyone for all the help in getting this release together! :smiley_cat:

**Pull request merged**
