### PR TITLE
migration to mkdocs

### PR DESCRIPTION
**Pull request by offirgolan**
I felt like the readme was getting way too long so I think it's a good idea to move to a docs library. Feel free to checkout this branch and go to [localhost:4200/docs](http://localhost:4200/docs)

### CODE REVIEW

**Comment by offirgolan** [comment]
Ready for review :smile:

**Comment by stefanpenner** [comment]
looking now :)

**Comment by stefanpenner** [comment]
LGTM – other then adding docs adds 8kloc to the repo. But "meh"

**Comment by offirgolan** [comment]
Docs are ignored by npm so I don't think that should be a problem

**Comment by stefanpenner** [comment]
> Docs are ignored by npm so I don't think that should be a problem

:+1:

**Comment by blimmer** [comment]
:heart_eyes:

**Comment by blimmer** [comment]
In general, I'd really like to see a nice ember + github compatible documentation generator. If it were easy to document code and generate a github markdown flavor docs file, it'd be a huge win. The only first-class documentation plugin (as far as I can tell) is ember-cli-yuidoc, which generates html.

**Comment by offirgolan** [comment]
I'm on vacation right now so I'll get this merged and setup sometime this weekend :)

**Pull request merged**
