### PR TITLE
Clear errors implementation

### PR DESCRIPTION
**Pull request by offirgolan**
Solves #81 

I do have a couple comments/concerns: 

1. Is clearErrors the correct naming for this?
2. When we clear an error message, should the result object be set to `isValid: true`? Or should we just clear the message?
3. Instead of updating the result object, maybe removing it all together from the result collection would make more sense?

Usage:

```js
obj.clearErrors();
obj.clearErrors('presence');
obj.clearErrors(['presence', 'length']);

obj.get('validations.attrs.foo').clearErrors();
// ....

### CODE REVIEW

**Comment by rox163** [comment]
IMHO -
For the naming, maybe clearValidationErrors? I guess clearErrors is a bit vague.
When we clear, I think it should be 'reset' to the state it was in when we first visited the page. I think isValid is set to false at that point, because the field would have no content? If isValid is true, then that might cause issues with styling the field based on its validity or maybe even submit button styling based on validity.

**Comment by offirgolan** [comment]
After some more testing, I've found that this problem is more complicated than I expected. The issue lies with modifying a result object outside of the main CP. If we clear a validation to its default state ( `message: null, isValid:true` ) the validation CP will not be updated again until its dependent keys change.

1. validate --> isValid: false
2. clearErrors --> isValid:true
3. validate --> isValid:true. This should ideally rerun the validations but really, nothing actually changed

Im sort of leaning to not needing to support this use case since it is more of a UX issue. Instead, maybe propogate validation types.

If you want to display all errors that are not `presence`, you can instead just do something like this...

```js
errors: computed('validations.errors', function() {
 return this.get('validations.errors').filter(e => e.type !== 'presence')
})
```

```hbs
{{#each errors as |error|}}
 {{error.message}}
{{/each}}
```

**Comment by rox163** [comment]
Well, in my case I was just trying to reset the form completely, clearing all errors and all fields, not specifics fields/errors. So I thought this could be driven by the library. I see your point about the specific error message display being a UX issue.

**Comment by offirgolan** [comment]
Gotcha. Let me spend more time on this and see if I can come up with a cleaner and better working solution.

**Comment by rox163** [comment]
So far this is what I added to my form component to try to clear error messages and content from all fields when Clear button is clicked - 
```
clearForm() {
this.get('fieldIds').forEach( (fieldId) => {
		this.set('form_' + fieldId, '');
		this.set('didValidate', false);
		this.set('validations.attrs.' + fieldId + '.isInvalid', false);			
                this.set('validations.attrs.' + fieldId + '.message', null);
		$('#form_' + fieldId).val("");
	});
}
```
Seems to work. I do see intermittent issues where sometimes I need to click on the button twice for it to work.

**Comment by rox163** [comment]
Got back to fixing my form up this week. Setting the invalid property and message doesnt work properly in my component, when I try to Clear the form of all errors and values. 
```
this.set('validations.attrs.' + fieldId + '.isInvalid', false);         
this.set('validations.attrs.' + fieldId + '.message', null);
```
First it says I must use Ember.set() to set these values. Then when i use Ember.set(), it says I cannot set these values because they are readonly.

**Comment by offirgolan** [comment]
That wont work since attrs.fieldId is a CP made of other CPs

You will have to do the following

```js
this.get(`validations.attrs.${fieldId}.content`).forEach(v => v.update({isValid: true, message: null}))
```

**Comment by rox163** [comment]
Thanks! That helped!
Next hurdle in this workflow - So clearing the form now works and the field values are cleared in the model too. The problem with setting isValid:true on each field though is if I clear the form and then click  my Submit button, it submits the empty model because it thinks all the fields are valid :(
```
 validateAndSubmit() {
      let {model, validations} = this.validateSync();
      this.set('didValidate', true);
      if (validations.get('isValid')) {
        this.get('on-submit')(model);
      }
    }
```

**Comment by offirgolan** [comment]
@rox163 I was able to approach this in a much simpler way that doesnt require any change for this library. I created a demo app to illustrate this

https://github.com/offirgolan/clear-cp-demo

Feel free to clone, `npm i && bower i` then `ember s` to see it in action. The demo is based on the demo app of this library but with a reset functionality. To see the changes I made, you can look at [this commit](https://github.com/offirgolan/clear-cp-demo/commit/0b22306da87396c0a7388150862c04b182ae3d40)

**Pull request closed without merging**
